name: demo-api-cloudrun

on:
  push:
    branches:
      - 'main'

env:
  PROJECT_ID: ${{ secrets.CLOUD_RUN_PROJECT_NAME }}
  REGION: europe-west9
  REPO_NAME: demoapi

jobs:
  build-and-deploy:
    name: Setup, Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Authentication with Google Cloud
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.CLOUD_RUN_SERVICE_ACCOUNT }}

      # Setup gcloud CLI/SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build the docker image
        run: |
          docker build -t temp-demoapi .

      - name: Tag the docker image
        run: |
          docker tag temp-demoapi gcr.io/${{ env.PROJECT_ID }}/demoapi:${{ github.sha }}

      - name: Push the image to the Google Container Registry (GCR)
        run: |
          docker push gcr.io/$PROJECT_ID/demoapi:${{ github.sha }}

      - name: Deploy
        run: |
          gcloud run deploy $REPO_NAME \
          --region $REGION \
          --image gcr.io/$PROJECT_ID/demoapi \
          --platform managed \
          --quiet
